spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: mail
    password: liurui_ruiqeradf123_123ll
    url: jdbc:mysql://82.157.162.121:3306/mall?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 82.157.162.121
    port: 5672
    username: guest
    password: guest
  redis:
    host: 82.157.162.121
    port: 6379
    password: _asdfasdfwf_fasdf123  # Redis服务器连接密码（默认为空）

eureka:
  client:
    service-url:
      defaleZone: http://localhost:8761/eureka/


server:
  port: 8763